p8105_hw3_ns3782
================
NSK
2024-10-13

# Problem 1

``` r
# Load libraries and import data

library(p8105.datasets)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
data("ny_noaa")
```

## Dataset Overview

The NY NOAA dataset contains 2595176 observations of 7 weather related
variables, corresponding to daily weather data collected from 747 unique
weather stations in New York City. The date range of the observations is
from 1981-01-01 to 2010-12-31.

Key variables and their types include: `id` (character, weather station
identifier), `date` (Date, YYYY-MM-DD), `prcp` (integer, precipitation),
`snow` (integer, snowfall), `snwd` (integer, snow depth), `tmax`
(character, maximum temperature), `tmin` (character, minimum
temperature).

Missing data is an issue in this dataset. The total number of missing
values across all variables is 3387623, which represents 18.65% of all
observations in the dataset.

For the id variable, there are 0 missing values (0% of total
observations). The date variable has 0 missing values (0% of total
observations). Precipitation (prcp) has 145838 missing values (5.62% of
total observations). For snowfall (snow), there are 381221 missing
values (14.69% of total observations). Snow depth (snwd) has 591786
missing values (22.8% of total observations). Maximum temperature (tmax)
has 1134358 missing values (43.71% of total observations). Minimum
temperature (tmin) has 1134420 missing values (43.71% of total
observations).

``` r
# Data cleaning

ny_noaa_clean <- ny_noaa %>%
  mutate(
    date = as.Date(date),
    year = lubridate::year(date),
    month = lubridate::month(date),
    day = lubridate::day(date),
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10
  )


# Most common snowfall values
ny_noaa_clean %>%
  count(snow) %>%
  arrange(desc(n)) %>%
  head(5)
```

    ## # A tibble: 5 × 2
    ##    snow       n
    ##   <int>   <int>
    ## 1     0 2008508
    ## 2    NA  381221
    ## 3    25   31022
    ## 4    13   23095
    ## 5    51   18274

## Most Common Snowfall values

The most common snowfall values for NYC are 0 mm (2008508 occurrences),
followed by NA (381221 occurrences). 0 is the most common, likely due to
New York City rarely having snow year round particularly in recent
years, while NA represents missing data. The next most common values are
25, 13, 51 mm, which are 1 inch, 0.5 inch, and 2 inches respectively.
These are indicative of typical light to moderate snowfall events, which
would be expected of New York City during colder months.

``` r
# Load libraries
library(ggplot2)

# Two-panel plot

temp_plot <- ny_noaa_clean %>%
  filter(month %in% c(1, 7), !is.na(tmax)) %>%
  group_by(id, year, month) %>%
  summarise(avg_tmax = mean(tmax, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = year, y = avg_tmax, group = id, color = id)) +
  geom_line(alpha = 0.3) +
  facet_wrap(~month, scales = "free_y", 
             labeller = labeller(month = c("1" = "January", "7" = "July"))) +
  labs(title = "Average Maximum Temperature in January and July by Station (Celsius)",
       x = "Year", y = "Average Max Temperature (Celsius)") +
  theme(legend.position = "none")
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

``` r
print(temp_plot)
```

![](p8105_hw3_ns3782_files/figure-gfm/problem_1_plot-1.png)<!-- -->

## Average max temperature in January and in July

There are several observations based on the two-panel plot showing the
average max temperature in January and in July in each station across
years. First, expected seasonal differences in maximum temperature are
observable between the winter and summer months in New York. July
temperatures are consistently higher on average (20-35°C) than January
temperatures (-10 to 10°C). Second, January temperatures appear to have
more variability than July temperatures, which may be typical for NYC’s
climate. Third, there is a spike in maximum temperatures for July 2010.
Several stations show temperatures reaching or exceeding 30°C. This
appears to be the highest point on the entire July graph, suggesting
that July 2010 may have been the hottest July in the 30-year period
shown. Lastly, concerning outliers. The month of January shows
comparatively more extreme outliers compared to July, with some years in
January observed to have unusually low or high temperatures. This is
especially apparent around 1982, where there is a dip in temperature
below -10°C. July has fewer extreme outliers, but there is a notable dip
around 1988 for one weather station to below 15°C suggesting a
significant weather event, or weather station recording error.

``` r
# Load required libraries 

library(tidyverse)
library(patchwork)
library(ggridges)

# Panel 1: tmax vs tmin as a line graph

p1_nyc_noaa_plot <- ny_noaa_clean %>%
  group_by(date) %>%
  summarise(avg_tmax = mean(tmax, na.rm = TRUE),
            avg_tmin = mean(tmin, na.rm = TRUE)) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = avg_tmax, color = "Maximum"), alpha = 0.7) +
  geom_line(aes(y = avg_tmin, color = "Minimum"), alpha = 0.7) +
  scale_color_manual(values = c("Maximum" = "red", "Minimum" = "blue")) +
  labs(title = "Average Daily Maximum and Minimum Temperatures in New York City (1981-2010)", x = "Date", y = "Temperature (Celsius)", color = "Temperature Type") +
  theme(legend.position = "bottom")

# Panel 2: Boxplot of snowfall values greater than 0 and less than 100

p2_nyc_noaa_plot <- ny_noaa_clean %>%
  filter(snow > 0, snow < 100) %>%
  ggplot(aes(x = factor(year), y = snow)) +
  geom_boxplot() +
  labs(title = "Distribution of snowfall in New York City (1981-2010)", x = "Year", y = "Snowfall (mm)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  


# Combine and print plot

print(p1_nyc_noaa_plot / p2_nyc_noaa_plot) 
```

![](p8105_hw3_ns3782_files/figure-gfm/problem_1_plot2-1.png)<!-- -->

# Problem 2

``` r
## Import and clean datasets

# Import and clean nhanes_covar csv

nhanes_covar <- read_csv("./data/nhanes_covar.csv", skip = 4) %>% 
  janitor::clean_names() 
```

    ## Rows: 250 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (5): SEQN, sex, age, BMI, education
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Import and clean results nhanes_accel csv

nhanes_accel <- read_csv("./data/nhanes_accel.csv") %>% 
  janitor::clean_names() 
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
